---

- name: Create the manifest files directory if it does not exist
  file:
    path: "/tmp/{{ kubernetes_pod_network_cni }}"
    state: directory
    mode: '0755'

- name: Download manifest files.
  get_url:
    url: "{{ item }}"
    dest: "/tmp/{{ kubernetes_pod_network_cni }}/{{ item | basename }}"
    mode: '0644'
  with_items: "{{ kubernetes_pod_network_manifest_files }}"

- name: Replace the CIDR settings.
  replace:
    path: "/tmp/{{ kubernetes_pod_network_cni }}/{{ item | basename }}"
    regexp: '(\s+)192\.168\.0\.0\/16(\s+.*)?$'
    replace: '\1{{ kubernetes_pod_network_cidr | regex_escape() }}\2'
    backup: yes
  with_items: "{{ kubernetes_pod_network_manifest_files }}"

- name: List manifest files.
  find:
    paths: "/tmp/{{ kubernetes_pod_network_cni }}"
    patterns: '*.yml,*.yaml'
  register: find_result

- name: Configure Calico networking.
  command: "kubectl apply -f {{ item.path }}"
  with_items: "{{ find_result.files }}"
  register: kubernetes_pod_network_result
  changed_when: "'created' in kubernetes_pod_network_result.stdout"
